name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile

  - pytorch=2.5.1

  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
    - transformers
    - diffusers
    - accelerate
    - huggingface-hub
    - ninja
    - xatlas
    - imageio
    - matplotlib
    - pyrallis
    - loguru
    - tqdm
